const bookingDetails = [
    {
      title: "Lakeside Bungalow",
      location: "Lake Tahoe, NV",
      status: "For Sale",
      bedrooms: 4,
      bathrooms: 3,
      sqft: 200,
      category: "Bungalow",
    },
    {
      title: "Hilltop Mansion",
      location: "Beverly Hills, CA",
      status: "Sold",
      bedrooms: 6,
      bathrooms: 5,
      sqft: 500,
      category: "Mansion",
    },
    {
      title: "Downtown Studio",
      location: "Chicago, IL",
      status: "For Rent",
      bedrooms: 1,
      bathrooms: 1,
      sqft: 60,
      category: "Studio",
    },
    {
      title: "Country Barnhouse",
      location: "Nashville, TN",
      status: "For Sale",
      bedrooms: 3,
      bathrooms: 2,
      sqft: 150,
      category: "Barnhouse",
    },
    {
      title: "Ocean Cliff Retreat",
      location: "Big Sur, CA",
      status: "For Rent",
      bedrooms: 2,
      bathrooms: 2,
      sqft: 160,
      category: "Retreat",
    },
    {
      title: "Modern Duplex",
      location: "Seattle, WA",
      status: "For Sale",
      bedrooms: 3,
      bathrooms: 2,
      sqft: 180,
      category: "Duplex",
    },
    {
      title: "Historic Manor",
      location: "Edinburgh, UK",
      status: "Sold",
      bedrooms: 5,
      bathrooms: 3,
      sqft: 320,
      category: "Manor",
    },
    {
      title: "Tropical Treehouse",
      location: "Maui, HI",
      status: "For Rent",
      bedrooms: 2,
      bathrooms: 1,
      sqft: 100,
      category: "Treehouse",
    },
    {
      title: "Rustic Farmhouse",
      location: "Amish Country, PA",
      status: "For Sale",
      bedrooms: 4,
      bathrooms: 2,
      sqft: 220,
      category: "Farmhouse",
    },
    {
      title: "Snowy Chalet",
      location: "Whistler, Canada",
      status: "For Rent",
      bedrooms: 3,
      bathrooms: 2,
      sqft: 190,
      category: "Chalet",
    },
    {
      title: "Suburban Home",
      location: "Austin, TX",
      status: "Sold",
      bedrooms: 3,
      bathrooms: 2,
      sqft: 170,
      category: "House",
    },
    {
      title: "Riverside Cottage",
      location: "Yorkshire, UK",
      status: "For Sale",
      bedrooms: 2,
      bathrooms: 1,
      sqft: 95,
      category: "Cottage",
    },
    {
      title: "Luxury Penthouse",
      location: "Miami, FL",
      status: "For Sale",
      bedrooms: 4,
      bathrooms: 4,
      sqft: 300,
      category: "Penthouse",
    },
    {
      title: "Vintage Flat",
      location: "Paris, France",
      status: "For Rent",
      bedrooms: 2,
      bathrooms: 1,
      sqft: 110,
      category: "Flat",
    },
    {
      title: "Island Bungalow",
      location: "Bora Bora",
      status: "Sold",
      bedrooms: 3,
      bathrooms: 2,
      sqft: 140,
      category: "Bungalow",
    },
    {
      title: "Cliffside Cabin",
      location: "Zion, UT",
      status: "For Sale",
      bedrooms: 2,
      bathrooms: 1,
      sqft: 125,
      category: "Cabin",
    },
  ];
  
  export default bookingDetails;
  