const wishlistData = [
    {
      id: 1,
      title: "Luxury Villa in Beverly Hills",
      location: "Beverly Hills, CA",
      beds: 5,
      baths: 3,
      sqft: 250,
      price: 5000,
      status: "For Sale",
      category: "Villa",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "Luxury Villa in Beverly Hills with modern amenities and scenic views.",
    },
    {
      id: 2,
      title: "Modern Apartment in NYC",
      location: "New York City, NY",
      beds: 2,
      baths: 2,
      sqft: 120,
      price: 3500,
      status: "Sold",
      category: "Apartment",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A sleek and stylish apartment in the heart of the city.",
    },
    {
      id: 3,
      title: "Oceanfront Condo in Miami",
      location: "Miami, FL",
      beds: 3,
      baths: 2,
      sqft: 180,
      price: 4200,
      status: "For Sale",
      category: "Condo",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "An oceanfront condo offering breathtaking views of the beach.",
    },
    {
      id: 4,
      title: "Penthouse in San Francisco",
      location: "San Francisco, CA",
      beds: 4,
      baths: 4,
      sqft: 300,
      price: 9500,
      status: "Sold",
      category: "Penthouse",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A luxurious penthouse in the heart of San Francisco with panoramic views.",
    },
    {
      id: 5,
      title: "Spacious Farmhouse in Texas",
      location: "Austin, TX",
      beds: 6,
      baths: 5,
      sqft: 400,
      price: 6500,
      status: "For Sale",
      category: "Farmhouse",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A spacious farmhouse offering peaceful living with wide-open spaces.",
    },
    {
      id: 6,
      title: "Luxury Loft in Downtown LA",
      location: "Los Angeles, CA",
      beds: 2,
      baths: 2,
      sqft: 150,
      price: 5000,
      status: "For Sale",
      category: "Loft",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A modern luxury loft in the heart of downtown LA with skyline views.",
    },
    {
      id: 7,
      title: "Mountain Cabin in Colorado",
      location: "Aspen, CO",
      beds: 4,
      baths: 3,
      sqft: 220,
      price: 4600,
      status: "Sold",
      category: "Cabin",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A cozy mountain cabin perfect for winter retreats and outdoor adventures.",
    },
    {
      id: 8,
      title: "Stylish Loft in Chicago",
      location: "Chicago, IL",
      beds: 3,
      baths: 2,
      sqft: 200,
      price: 5500,
      status: "For Sale",
      category: "Loft",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A stylish, modern loft with a large open floor plan in Chicago's downtown.",
    },
    {
      id: 9,
      title: "Beach House in Malibu",
      location: "Malibu, CA",
      beds: 4,
      baths: 3,
      sqft: 300,
      price: 9500,
      status: "For Sale",
      category: "Beach House",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A beachfront property in Malibu with stunning views of the Pacific Ocean.",
    },
    {
      id: 10,
      title: "Cozy Cottage in Vermont",
      location: "Woodstock, VT",
      beds: 2,
      baths: 1,
      sqft: 110,
      price: 2400,
      status: "Sold",
      category: "Cottage",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A charming, cozy cottage in a quaint Vermont village.",
    },
    {
      id: 11,
      title: "Elegant Mansion in Beverly Hills",
      location: "Beverly Hills, CA",
      beds: 8,
      baths: 6,
      sqft: 500,
      price: 12000,
      status: "For Sale",
      category: "Mansion",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "An elegant mansion with exquisite architecture and expansive grounds.",
    },
    {
      id: 12,
      title: "Charming Townhouse in Brooklyn",
      location: "Brooklyn, NY",
      beds: 3,
      baths: 2,
      sqft: 180,
      price: 4000,
      status: "For Sale",
      category: "Townhouse",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A charming townhouse in the heart of Brooklyn with a modern touch.",
    },
    {
      id: 13,
      title: "Chic Studio in Paris",
      location: "Paris, France",
      beds: 1,
      baths: 1,
      sqft: 70,
      price: 2500,
      status: "For Sale",
      category: "Studio",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A chic studio apartment in one of the most fashionable neighborhoods of Paris.",
    },
    {
      id: 14,
      title: "Luxury Skyscraper in Dubai",
      location: "Dubai, UAE",
      beds: 6,
      baths: 5,
      sqft: 350,
      price: 12000,
      status: "For Sale",
      category: "Skyscraper",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A luxurious skyscraper in the heart of Dubai with unparalleled views.",
    },
    {
      id: 15,
      title: "Contemporary Villa in Bali",
      location: "Bali, Indonesia",
      beds: 5,
      baths: 4,
      sqft: 300,
      price: 7000,
      status: "Sold",
      category: "Villa",
      cardImage:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
      description: "A modern villa offering serene surroundings and luxury living in Bali.",
    }
  ];
export default wishlistData;  