// import NextAuthSectionProvider from "@/components/NextAuthSectionProvider";
import "../globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { Breadcrumb, BreadcrumbList } from "@/components/ui/breadcrumb";
import { DarkModeToggle } from "@/components/ui/DarkModeToggle";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="">
      {/* <NextAuthSectionProvider> */}
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12  border-gray-200 border-b">
              <div className="flex items-center sm:mx-8 lg:mx-14">
                <div className="flex items-center ">
                  <SidebarTrigger className="ml-3.5 sm:-ml-1" />
                  <Separator
                    orientation="vertical"
                    className="mr-2 data-[orientation=vertical]:h-4"
                  />
                  <Breadcrumb>
                    <BreadcrumbList>
                      <DarkModeToggle />
                    </BreadcrumbList>
                  </Breadcrumb>
                </div>
              </div>
            </header>
            <div className="py-2 sm:mx-8 lg:mx-14 container mx-auto">
              {children}
            </div>
          </SidebarInset>
        </SidebarProvider>
      {/* </NextAuthSectionProvider> */}
    </div>
  );
}
