import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthSectionProvider from "@/components/NextAuthSectionProvider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSectionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <main className="">{children}</main>
          <Toaster/>
        </body>
      </NextAuthSectionProvider>
    </html>
  );
}
