import Footer from "../Components/Sherd/Footer";
import NavBer from "../Components/Sherd/NavBer";
import "../globals.css";

export const metadata = {
  title: "HouseLease || Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div className="sticky top-0 z-50">
        <NavBer />
      </div>
      <div className="min-h-[calc(100vh-350px)]"> {children}</div>
      <Footer />
    </>
  );
}
